const scopes = [
    'ads_management',
    'ads_read',
    // 'attribution_read',
    // 'business_management',
    // 'email',
    // 'groups_access_member_info',
    // 'instagram_basic',
    // 'instagram_manage_comments',
    // 'instagram_manage_insights',
    // 'leads_retrieval',
    // 'pages_manage_ads',
    // 'pages_manage_cta',
    // 'pages_manage_instant_articles',
    // 'pages_manage_engagement',
    // 'pages_manage_metadata',
    // 'pages_manage_posts',
    // 'pages_messaging',
    // 'pages_read_engagement',
    // 'pages_read_user_content',
    // 'pages_show_list',
    // 'publish_to_groups',
    // 'read_insights',
    // 'user_age_range',
    // 'user_birthday',
    // 'user_friends',
    // 'user_gender',
    // 'user_hometown',
    // 'user_likes',
    // 'user_link',
    // 'user_location',
    // 'user_photos',
    // 'user_posts',
    // 'user_videos',
    // 'whatsapp_business_management',
    // 'catalog_management',
]

export default scopes